pipeline:
  name: aggregate
description: |
  calculate aggregate statistics for normalized images
input:
  pfs:
    repo: normalize
    glob: "/"
transform:
  cmd:
    - "python"
    - "/aggregate.py"
  image: "pachyderm-demo:1.0"
resource_requests:
  cpu: 0.1
  memory: "128M"
resource_limits:
  cpu: 0.2
  memory: "256M"
sidecar_resource_limits:
  cpu: 0.1
  memory: "128M"
autoscaling: true
parallelism_spec:
  constant: 1