pipeline:
  name: bbox
description: |
  crop to bounding box
input:
  join:
    - pfs:
        repo: images
        glob: "/(*).jpg"
        join_on: $1
    - pfs:
        repo: labels
        glob: "/(*)"
        join_on: $1
transform:
  cmd:
    - "python"
    - "/bbox.py"
  image: "pachyderm-demo:1.0"
resource_requests:
  cpu: 0.1
  memory: "128M"
resource_limits:
  cpu: 0.1
  memory: "128M"
sidecar_resource_limits:
  cpu: 0.1
  memory: "128M"
autoscaling: true
parallelism_spec:
  constant: 4