pipeline:
  name: montage
description: |
  join raw and normalized images
input:
  join:
    - pfs:
        repo: bbox
        glob: "/(*)"
        join_on: $1
    - pfs:
        repo: normalize
        glob: "/(*)"
        join_on: $1
transform:
  cmd:
    - "python"
    - "/montage.py"
  image: "pachyderm-demo:1.0"
resource_requests:
  cpu: 0.1
  memory: "128M"
resource_limits:
  cpu: 0.1
  memory: "128M"
sidecar_resource_limits:
  cpu: 0.1
  memory: "128M"
autoscaling: true
parallelism_spec:
  constant: 4