pipeline:
  name: normalize
description: |
  normalize images
input:
  pfs:
    repo: "bbox"
    glob: "/*"
transform:
  cmd:
    - "python"
    - "/normalize.py"
  image: "pachyderm-demo:1.0"
resource_requests:
  cpu: 0.1
  memory: "128M"
resource_limits:
  cpu: 0.1
  memory: "128M"
sidecar_resource_limits:
  cpu: 0.1
  memory: "128M"
autoscaling: true
parallelism_spec:
  constant: 4